package com.krm.contants;

public enum Event {

    FRIEND_REQUEST_RECEIVE,
    FRIEND_REQUEST_SENT,
    FRIEND_REQUEST_CANCELED,
    FRIEND_REQUEST_REJECTED,
    MESSAGE_RECEIVE,
    MESSAGE_DELIVERED,
    MESSAGE_SENT,
    PROFILE_CHANGE
}
